services:
  iptv-balance:
    image: cybrp/iptv-balance:latest
    container_name: iptv-balance
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - HOST=0.0.0.0
      - PORT=80
    volumes:
      - iptv-data:/data

volumes:
  iptv-data:
